# Generated by Django 3.2.7 on 2021-10-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_info_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_app', models.TextField(null=True)),
                ('array_img', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('date_up', models.CharField(max_length=255, null=True)),
                ('time_up', models.CharField(max_length=255, null=True)),
                ('text_body', models.TextField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
