# Generated by Django 3.2.7 on 2021-10-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
