# Generated by Django 3.2.7 on 2021-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_post_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='id_app_post',
            field=models.TextField(default=''),
        ),
    ]
