# Generated by Django 3.2.7 on 2021-10-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_post_id_app_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='date_up',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='time_up',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
