# Generated by Django 3.2.7 on 2021-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='array_img',
            field=models.TextField(default='', null=True),
        ),
    ]
