# Generated by Django 3.2.7 on 2021-10-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_post_array_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='id_app_post',
            field=models.TextField(default='', null=True),
        ),
    ]
